CREATE DATABASE IF NOT EXISTS COMMUNITY;
DROP TABLE IF EXISTS `COMMUNITY`.`USERS`;
CREATE TABLE `COMMUNITY`.`USERS`(
`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
`account` VARCHAR(20) NOT NULL,
`password` TEXT NOT NULL,
`nick_name` VARCHAR(50) NOT NULL,
`deleted` BOOLEAN NOT NULL DEFAULT FALSE,
`updated_at` TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
`created_at` TIMESTAMP NOT NULL DEFAULT NOW(),
PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;